### ISSUE TITLE
Buenas, queria preguntar si no tenias lo mismo que esta en la repo en algun drive asi es mas facil de navegar. Medio complicado navegar y ver todo en github

### ISSUE THREAD

**Issue by JoacoPorro** [gcc-cdimatteo/Sistemas-Operativos-75.08#1]

**Comment by gcc-cdimatteo** [comment]
Buenas, no, no está en drive. La idea es que bajen el repo como zip para que puedan acceder a los archivos más fácil.

Inicialmente era una carpeta en Drive así que si bajas el zip, lo descomprimís y lo volvés a subir a drive no deberías tener problema!

**Comment by JoacoPorro** [comment]
Muchas gracias

**Comment by JoacoPorro** [comment]
Otra cosa mas, yo estoy haciendo unas repos asi: https://github.com/jporro/ProbabilidadYEstadistica. Quiero que sean una recopilacion lo mas completa que se pueda de las materias. Esta bien si subo partes de cosas de tus repos o directamente todo la repo como drives?

**Comment by gcc-cdimatteo** [comment]
A ver, mi repo es público, no puedo prohibirte que descargues lo que hay acá y lo vuelvas a poner en otro lugar. Podés poner algún link a mi repo como reconocimiento/bibliografía fuente.
Yo tengo un poco de material tomado de otros alumnos pero realmente nunca puse fuentes porque son compilados que se van pasando y desconozco a quién referenciarlos. Pero si podés incluirme para que mi cuenta tenga más interacción sería bueno :)

**Comment by JoacoPorro** [comment]
ajaj dale
